import React, { Component } from 'react'
import './about.css'

class Aboutus extends Component {
  render () {
    return (

      <div className='allabout'>

        <br /><br /><br />
        <div className='container center-content'>
          <h1 style={{ 'color': 'white' }}>Yantragene</h1>

        </div>
        <div className='center-content'>
          <hr />
          <p>
             The Technical Fest plays an important role in the college curriculum.” Yantragene” is the two-day technical fest organized in F.G.I.E.T. and the 4th edition of this annual inter-college fest is going to be held on April 11 to April 12,2019. This event was first organized in 2016 with a motto to give a platform to the young brains to show their skills and compete with others to find the best. To motivate the spirit of participants, cash prizes, certificates along with various other exciting prizes are awarded the winners as well as to cheer up the others there are certification for participation too. It is not just about the competitions but also an event where a lot of those new ideas are seen live and learn more and be inspired. This inspiring event that happens every year in college guides the students to dream bigger and make those dreams come true.
          </p>
          <p>
             Yantragene consists of a number of events for a variety of interests or skills of the students-<br />
            <span className='heading'>PUBG-</span>Enter into the No Man’s Land and Claim What’s yours!! Fight with the sneakiest killers and Most Ferocious players from all around, to become the deadliest warrior of All. Register, to Win not just a Chicken Dinner but much more.<br />
            <span className='heading'>Webbit-</span>This event is for those who are interested in web development in which the front end skills of web developers are checked i.e., coding challenge.<br />
            <span className='heading'>AppMania-</span>Event to show your talent of Application development for any of these platforms using suitable Languages-Web Application, Standalone Application or Android Application.<br />
            <span className='heading'>ZumoWar-</span>Mad about robos? Want to see them fight? In this mechanized modern world, this madness can be brought to next level by making your robo cold hearted in the arena by using destructive tools and fight against your rivals. The arena awaits…<br />
            <span className='heading'>RoboSoccer-</span>Soccer is blowing everybody’s mind and nowadays we wish to do that all sitting at a place along with this want to feel the joy of playing that. So, train your bots to make a goal which can change the game.<br />
            <span className='heading'>AirFray-</span>Making a paper plane is always fun specially in the college or school campus. So, here in Yantragene there is a challenge of making a paper plane that will travel the longest distance in air.<br />
            <span className='heading'>SkyRC-</span>To distinct our Aeronautical Department from all others a special event is there in the fest.Here you will enjoy watching teams tackle courses and challenges by their own RC planes and touch the sky.<br />
            <span className='heading'>BridgeIt-</span>The most popular event witnessing the max. number of participants and some spectacular structures which have the capacity to mesmerize the crowd is BridgeIt. Construction of a suspension bridge using ice-cream sticks with ultimate load capacity and bridge weight.<br />
            <span className='heading'>RoboRace-</span>This is an event where RC cars overcome obstacles on a difficult path designed specifically to test the limits of the car. The car to finish the path in the shortest time wins it all.<br />
            <span className='heading'>Techy shots-</span>t’s all about preparing a model that accumulates maximum force generated by chemical reactions and perform the various tasks of the respective rounds.<br />
            <span className='heading'>DigiCanva-</span>Event for creative people with designing skills using digital tools and software who can manipulate without distorting real images but with basic enhancements are the one for this event.<br />
            <span className='heading'>AlgoSense-</span>Coding fever!! The programming competition for testing the coding skills of the students and spinning the wheels of the brains.<br />
            <span className='heading'>Hovermania-</span>Hovercrafts, vehicles capable of running on all surfaces, be it land, glass water, concrete, snow or grass, just name it.
Prepare your RC Hovercrafts and get ready for the showdown<br />
            <span className='heading'>Robo balloon Fight-</span>Robo ballon fight is a form of robot competition in which two or more custom-built machines use varied methods of destroying  the other robo's ballon. The machines are generally remote-controlled vehicles rather than autonomous robots.
Competitor robots come in a variety of designs, with different strategies for winning fights.
A robot loses when its ballon bursts , due to damage inflicted from the other robot's pin/needle.<br />
            <span className='heading'>Embedded Expo-</span>Embedded Expo provides a platform to inspire the innovator within to come up with their working and non-
              working model that can improve the efficiency of presently employed system or provide an innovative
              solution to real time problem. Some of the current challenges exist in fields associated with general
              hardware implementation, social and rural life and green technology. The creative and ethical use of
              technology helps to transform the society lets come and take few steps<br />
            <span className='heading'>Contraption-</span>Contraption is a chain of different 'energy conversion' steps, in which one step triggers the next one leading to completion of final task. In this event participants are asked to make a Contraption system which will hit a skittle arrangement.<br /><br />
          </p>
          <hr />
        </div>

        <ul class='icon-position icon11' >
          <li><a href='https://www.facebook.com/yantragene.fgiet/'><i class='fa fa-facebook' aria-hidden='true' /></a></li>
          <li><a href='https://instagram.com/yantragene?utm_source=ig_profile_share&igshid=1l8gqgkq6cnjx'><i class='fa fa-instagram' aria-hidden='true' /></a></li>
        </ul>
      </div>

    )
  }
}
export default Aboutus
