# Generated by Django 2.0.6 on 2019-03-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('epic', models.ImageField(blank=True, upload_to='images/events')),
                ('eintro', models.TextField()),
                ('econtent', models.TextField()),
                ('max_size_of_team', models.IntegerField(default=1)),
                ('c1name', models.CharField(max_length=255)),
                ('c1pic', models.ImageField(blank=True, upload_to='images/coordinators')),
                ('c1mobile', models.CharField(max_length=12)),
                ('c2name', models.CharField(max_length=255)),
                ('c2pic', models.ImageField(blank=True, upload_to='images/coordinators')),
                ('c2mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('other_mambers', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
