# Generated by Django 2.0.6 on 2019-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='other_mambers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
