# Generated by Django 2.0.6 on 2019-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190326_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event_name',
            field=models.CharField(default='algosense', max_length=40),
        ),
    ]
