# Generated by Django 2.0.6 on 2019-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default='2019-02-02'),
            preserve_default=False,
        ),
    ]
